name: "Install python and dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: uv sync
