services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_NAME: "books"
      DATABASE_USER: "books"
      DATABASE_PASSWORD: "books"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DEVELOPMENT_MODE: "false"
    depends_on:
      - db
    volumes:
      - .:/app
      - venv:/app/.venv
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: "books"
      POSTGRES_PASSWORD: "books"
      POSTGRES_DB: "books"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  venv:
